name: ml_notes
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - python=3.7
  - pandas=0.25.3
  - numpy
  - matplotlib
  - ipython
  - seaborn
  - jupyter
  - scikit-learn
  - scikit-plot=0.3.7
  - statsmodels
  - pip
  - tqdm
  - cython
  - feather-format
  - psutil
  - pytest
  - pyyaml
  - xlrd
  - plotly=4.4.1
  - category_encoders
  - pip:
    - treeinterpreter
    - Kaggler
